name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: compile test
      run: gcc test_jurossimples.c -o test_jurossimples

    - name: execute test
      run: ./test_jurossimples

    - name: compile main
      run: gcc jurossimples.c -o jurossimples

    - name: execute main
      run: ./jurossimples 100 50 10

    - name: mostrar o conteúdo do arquivo criado
      run: cat jurossimples.txt
